name: event_finder
description: A new Flutter project.

version: 1.0.0+1 # Tambahkan ini (build name 1.0.0, build number 1)

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.4
  # another_flushbar: 1.10.29
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cloud_firestore: 5.5.0
  cloud_firestore_platform_interface: 6.5.0
  cloud_firestore_web: 4.3.4
  collection: 1.19.0
  equatable: 2.0.5
  firebase_auth: 5.3.3
  firebase_core: 3.8.0
  firebase_core_platform_interface: 5.3.0
  firebase_core_web: 2.18.1
  fluttertoast: 8.0.9
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: ^6.2.1
  google_sign_in: 6.2.1
  http: 1.2.2
  intl: 0.19.0
  json_path: 0.7.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.4
  provider: 6.1.2
  rxdart: 0.27.7
  shared_preferences: 2.3.2
  sign_in_with_apple: 6.1.2
  sqflite: 2.3.3+1
  stream_transform: 2.1.0
  timeago: 3.6.1
  url_launcher: 6.3.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/res/assets/images/
